// Datos mock generados por gen_mock.js — estructura idéntica a los 5 archivos reales.
var MOCK = {
 "projMeta": {
  "AUR-24": "Aurora · Retail",
  "BOR-24": "Borealis · Banca",
  "CIT-24": "Citrino · Salud",
  "DEL-24": "Delta · Energía",
  "EBA-24": "Ébano · Telco",
  "FLO-24": "Floral · Consumo",
  "GEO-24": "Geo · Minería"
 },
 "refDate": "2026-06-08",
 "pc": [
  {
   "ID": 1,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 2,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 3,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 5,
   "Feedback y apoyo": 6,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 6,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 5,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "Diego se la jugó con el cliente esta semana, impecable.",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 4,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 6,
   "Feedback y apoyo": 6,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 6,
   "Rol en el desarrollo de la empresa": 5,
   "Equilibrio vida/trabajo": 6,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 5,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 6,
   "Feedback y apoyo": 6,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 6,
   "Rol en el desarrollo de la empresa": 5,
   "Equilibrio vida/trabajo": 6,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 6,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 6,
   "Desafío y desarrollo": 4,
   "Feedback y apoyo": 5,
   "Confianza para aportar": 6,
   "Reconocimiento de líderes": 5,
   "Rol en el desarrollo de la empresa": 5,
   "Equilibrio vida/trabajo": 4,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 7,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 6,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 6,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 6,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 8,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 6,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 6,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 6,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 9,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 6,
   "Desafío y desarrollo": 5,
   "Feedback y apoyo": 3,
   "Confianza para aportar": 6,
   "Reconocimiento de líderes": 5,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 5,
   "Comentario general": "",
   "Nombre del proyecto": "AUR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 10,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 11,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 12,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 13,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 14,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 15,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 16,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 17,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 18,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "BOR-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 19,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 20,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 21,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 6,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "Valentina aprende rapidísimo, gran aporte.",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 22,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 23,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 24,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 6,
   "Confianza para aportar": 7,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 25,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 8,
   "Feedback y apoyo": 8,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 8,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 8,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 26,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 8,
   "Feedback y apoyo": 8,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 8,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 8,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 27,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 8,
   "Desafío y desarrollo": 8,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 8,
   "Rol en el desarrollo de la empresa": 7,
   "Equilibrio vida/trabajo": 8,
   "Comentario general": "",
   "Nombre del proyecto": "CIT-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 28,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 29,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 30,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 31,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 32,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 33,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "DEL-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 34,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 35,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 36,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociado"
  },
  {
   "ID": 37,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 38,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 39,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 40,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 41,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 42,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "EBA-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Practicante"
  },
  {
   "ID": 43,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 44,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 45,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 46,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 47,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 48,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "FLO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 49,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 50,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 51,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Asociada"
  },
  {
   "ID": 52,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Marzo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 53,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Abril 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  },
  {
   "ID": 54,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo electrónico": "",
   "Mes": "Mayo 2026",
   "Disfrute en Summa": 7,
   "Desafío y desarrollo": 7,
   "Feedback y apoyo": 7,
   "Confianza para aportar": 8,
   "Reconocimiento de líderes": 7,
   "Rol en el desarrollo de la empresa": 6,
   "Equilibrio vida/trabajo": 7,
   "Comentario general": "",
   "Nombre del proyecto": "GEO-24",
   "Reconocimiento a un compañero": "",
   "Otro comentario": "",
   "Cargo": "Analista"
  }
 ],
 "ps": [
  {
   "ID": 1,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Camila Rojas",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-05-20",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 2,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Diego Fuentes",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-05-20",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 3,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Javiera Soto",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-05-20",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 4,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Camila Rojas",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-06-04",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "Sí",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 5,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Diego Fuentes",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-06-04",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "No",
   "¿Has trabajado fines de semana?": "Sí",
   "¿Sientes riesgo de burnout?": "Sí",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Carga muy alta las últimas semanas.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 6,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Javiera Soto",
   "Código de proyecto": "AUR-24",
   "Fecha Pit Stop": "2026-06-04",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "No",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 7,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Matías Vera",
   "Código de proyecto": "BOR-24",
   "Fecha Pit Stop": "2026-06-03",
   "Carga de trabajo razonable (1-10)": 2,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "Sí",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 8,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Fernanda Lillo",
   "Código de proyecto": "BOR-24",
   "Fecha Pit Stop": "2026-06-03",
   "Carga de trabajo razonable (1-10)": 3,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 9,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Ignacio Reyes",
   "Código de proyecto": "BOR-24",
   "Fecha Pit Stop": "2026-06-03",
   "Carga de trabajo razonable (1-10)": 3,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 10,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Tomás Herrera",
   "Código de proyecto": "DEL-24",
   "Fecha Pit Stop": "2026-05-10",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 11,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Catalina Núñez",
   "Código de proyecto": "DEL-24",
   "Fecha Pit Stop": "2026-05-10",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 12,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Antonia Pérez",
   "Código de proyecto": "CIT-24",
   "Fecha Pit Stop": "2026-06-02",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 13,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Sebastián Díaz",
   "Código de proyecto": "CIT-24",
   "Fecha Pit Stop": "2026-06-02",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 14,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Valentina Muñoz",
   "Código de proyecto": "CIT-24",
   "Fecha Pit Stop": "2026-06-02",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 15,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Rodrigo Castro",
   "Código de proyecto": "EBA-24",
   "Fecha Pit Stop": "2026-06-05",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 16,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Isidora Vargas",
   "Código de proyecto": "EBA-24",
   "Fecha Pit Stop": "2026-06-05",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 17,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Benjamín Tapia",
   "Código de proyecto": "EBA-24",
   "Fecha Pit Stop": "2026-06-05",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 18,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Francisca Morales",
   "Código de proyecto": "FLO-24",
   "Fecha Pit Stop": "2026-06-01",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 19,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Martín Silva",
   "Código de proyecto": "FLO-24",
   "Fecha Pit Stop": "2026-06-01",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 20,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Josefa Contreras",
   "Código de proyecto": "GEO-24",
   "Fecha Pit Stop": "2026-06-04",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  },
  {
   "ID": 21,
   "Hora de inicio": "",
   "Hora de finalización": "",
   "Correo": "",
   "Nombre": "Lucas Bravo",
   "Código de proyecto": "GEO-24",
   "Fecha Pit Stop": "2026-06-04",
   "Carga de trabajo razonable (1-10)": 7,
   "Claridad de objetivos (1-10)": 8,
   "Relación con el equipo (1-10)": 7,
   "Aprendizaje en el proyecto (1-10)": 8,
   "¿Cuentas con el apoyo del líder?": "Sí",
   "¿Tienes la información para avanzar?": "Sí",
   "¿El cliente colabora adecuadamente?": "Sí",
   "¿Te sientes con energía?": "Sí",
   "¿Has trabajado fines de semana?": "No",
   "¿Sientes riesgo de burnout?": "No",
   "¿Recomendarías seguir en este proyecto?": "Sí",
   "¿Qué está funcionando bien?": "El equipo está alineado.",
   "¿Qué mejorarías?": "Más claridad en prioridades.",
   "Comentarios adicionales": ""
  }
 ],
 "tr": [
  {
   "Nombre": "Diego",
   "Apellido": "Fuentes",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/21/2026",
   "Hora de solicitud (local)": "9:20PM",
   "Fecha de inicio (local)": "05/21/2026",
   "Hora de inicio (local)": "9:20PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/21/2026",
   "Hora de llegada (local)": "9:20PM",
   "Monto": "7900",
   "Programa": "AUR-24"
  },
  {
   "Nombre": "Matías",
   "Apellido": "Vera",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/21/2026",
   "Hora de solicitud (local)": "7:40PM",
   "Fecha de inicio (local)": "05/21/2026",
   "Hora de inicio (local)": "7:40PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/21/2026",
   "Hora de llegada (local)": "7:40PM",
   "Monto": "7900",
   "Programa": "BOR-24"
  },
  {
   "Nombre": "Sebastián",
   "Apellido": "Díaz",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/21/2026",
   "Hora de solicitud (local)": "6:50PM",
   "Fecha de inicio (local)": "05/21/2026",
   "Hora de inicio (local)": "6:50PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/21/2026",
   "Hora de llegada (local)": "6:50PM",
   "Monto": "7900",
   "Programa": "CIT-24"
  },
  {
   "Nombre": "Diego",
   "Apellido": "Fuentes",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/28/2026",
   "Hora de solicitud (local)": "9:42PM",
   "Fecha de inicio (local)": "05/28/2026",
   "Hora de inicio (local)": "9:42PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/28/2026",
   "Hora de llegada (local)": "9:42PM",
   "Monto": "7900",
   "Programa": "AUR-24"
  },
  {
   "Nombre": "Javiera",
   "Apellido": "Soto",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/28/2026",
   "Hora de solicitud (local)": "10:15PM",
   "Fecha de inicio (local)": "05/28/2026",
   "Hora de inicio (local)": "10:15PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/28/2026",
   "Hora de llegada (local)": "10:15PM",
   "Monto": "7900",
   "Programa": "AUR-24"
  },
  {
   "Nombre": "Camila",
   "Apellido": "Rojas",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/29/2026",
   "Hora de solicitud (local)": "9:05PM",
   "Fecha de inicio (local)": "05/29/2026",
   "Hora de inicio (local)": "9:05PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/29/2026",
   "Hora de llegada (local)": "9:05PM",
   "Monto": "7900",
   "Programa": "AUR-24"
  },
  {
   "Nombre": "Fernanda",
   "Apellido": "Lillo",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/29/2026",
   "Hora de solicitud (local)": "12:35AM",
   "Fecha de inicio (local)": "05/29/2026",
   "Hora de inicio (local)": "12:35AM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/29/2026",
   "Hora de llegada (local)": "12:35AM",
   "Monto": "7900",
   "Programa": "BOR-24"
  },
  {
   "Nombre": "Matías",
   "Apellido": "Vera",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/28/2026",
   "Hora de solicitud (local)": "8:50PM",
   "Fecha de inicio (local)": "05/28/2026",
   "Hora de inicio (local)": "8:50PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/28/2026",
   "Hora de llegada (local)": "8:50PM",
   "Monto": "7900",
   "Programa": "BOR-24"
  },
  {
   "Nombre": "Sebastián",
   "Apellido": "Díaz",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/28/2026",
   "Hora de solicitud (local)": "9:30PM",
   "Fecha de inicio (local)": "05/28/2026",
   "Hora de inicio (local)": "9:30PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/28/2026",
   "Hora de llegada (local)": "9:30PM",
   "Monto": "7900",
   "Programa": "CIT-24"
  },
  {
   "Nombre": "Antonia",
   "Apellido": "Pérez",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/29/2026",
   "Hora de solicitud (local)": "9:50PM",
   "Fecha de inicio (local)": "05/29/2026",
   "Hora de inicio (local)": "9:50PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/29/2026",
   "Hora de llegada (local)": "9:50PM",
   "Monto": "7900",
   "Programa": "CIT-24"
  },
  {
   "Nombre": "Martín",
   "Apellido": "Silva",
   "Email": "",
   "Servicio": "UberX",
   "Ciudad": "Santiago",
   "Fecha de solicitud (local)": "05/28/2026",
   "Hora de solicitud (local)": "7:10PM",
   "Fecha de inicio (local)": "05/28/2026",
   "Hora de inicio (local)": "7:10PM",
   "Origen": "Oficina Summa",
   "Destino": "Domicilio",
   "Distancia (km)": "8.4",
   "Fecha de llegada (local)": "05/28/2026",
   "Hora de llegada (local)": "7:10PM",
   "Monto": "7900",
   "Programa": "FLO-24"
  }
 ],
 "vac": [
  {
   "Empleado - Nombre Completo": "Camila Rojas",
   "Empleado - Cargo": "Asociada",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Diego Fuentes",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "10,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "6,0"
  },
  {
   "Empleado - Nombre Completo": "Javiera Soto",
   "Empleado - Cargo": "Practicante",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Matías Vera",
   "Empleado - Cargo": "Asociado",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Fernanda Lillo",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Ignacio Reyes",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Antonia Pérez",
   "Empleado - Cargo": "Asociada",
   "Vacaciones - Vacaciones tomadas a futuro legales": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "9,5",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "7,0"
  },
  {
   "Empleado - Nombre Completo": "Sebastián Díaz",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Valentina Muñoz",
   "Empleado - Cargo": "Practicante",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Tomás Herrera",
   "Empleado - Cargo": "Asociado",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Catalina Núñez",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Rodrigo Castro",
   "Empleado - Cargo": "Asociado",
   "Vacaciones - Vacaciones tomadas a futuro legales": "5,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "12,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "6,5"
  },
  {
   "Empleado - Nombre Completo": "Isidora Vargas",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Benjamín Tapia",
   "Empleado - Cargo": "Practicante",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Francisca Morales",
   "Empleado - Cargo": "Asociada",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Martín Silva",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Josefa Contreras",
   "Empleado - Cargo": "Asociada",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Lucas Bravo",
   "Empleado - Cargo": "Analista",
   "Vacaciones - Vacaciones tomadas a futuro legales": "3,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "4,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "2,0"
  },
  {
   "Empleado - Nombre Completo": "Paula Godoy",
   "Empleado - Cargo": "Asociada",
   "Vacaciones - Vacaciones tomadas a futuro legales": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro legales": "11,0",
   "Vacaciones - Vacaciones tomadas a futuro administrativos": "0,0",
   "Vacaciones - Saldo vacaciones tomadas a futuro administrativos": "6,0"
  }
 ],
 "proj": [
  {
   "Código": "AUR-24",
   "Nombre": "Camila Rojas",
   "Cargo": "Asociada"
  },
  {
   "Código": "AUR-24",
   "Nombre": "Diego Fuentes",
   "Cargo": "Analista"
  },
  {
   "Código": "CIT-24",
   "Nombre": "Diego Fuentes",
   "Cargo": "Analista"
  },
  {
   "Código": "AUR-24",
   "Nombre": "Javiera Soto",
   "Cargo": "Practicante"
  },
  {
   "Código": "BOR-24",
   "Nombre": "Matías Vera",
   "Cargo": "Asociado"
  },
  {
   "Código": "BOR-24",
   "Nombre": "Fernanda Lillo",
   "Cargo": "Analista"
  },
  {
   "Código": "BOR-24",
   "Nombre": "Ignacio Reyes",
   "Cargo": "Analista"
  },
  {
   "Código": "CIT-24",
   "Nombre": "Antonia Pérez",
   "Cargo": "Asociada"
  },
  {
   "Código": "CIT-24",
   "Nombre": "Sebastián Díaz",
   "Cargo": "Analista"
  },
  {
   "Código": "CIT-24",
   "Nombre": "Valentina Muñoz",
   "Cargo": "Practicante"
  },
  {
   "Código": "DEL-24",
   "Nombre": "Tomás Herrera",
   "Cargo": "Asociado"
  },
  {
   "Código": "DEL-24",
   "Nombre": "Catalina Núñez",
   "Cargo": "Analista"
  },
  {
   "Código": "EBA-24",
   "Nombre": "Catalina Núñez",
   "Cargo": "Analista"
  },
  {
   "Código": "EBA-24",
   "Nombre": "Rodrigo Castro",
   "Cargo": "Asociado"
  },
  {
   "Código": "EBA-24",
   "Nombre": "Isidora Vargas",
   "Cargo": "Analista"
  },
  {
   "Código": "EBA-24",
   "Nombre": "Benjamín Tapia",
   "Cargo": "Practicante"
  },
  {
   "Código": "FLO-24",
   "Nombre": "Francisca Morales",
   "Cargo": "Asociada"
  },
  {
   "Código": "FLO-24",
   "Nombre": "Martín Silva",
   "Cargo": "Analista"
  },
  {
   "Código": "GEO-24",
   "Nombre": "Josefa Contreras",
   "Cargo": "Asociada"
  },
  {
   "Código": "GEO-24",
   "Nombre": "Lucas Bravo",
   "Cargo": "Analista"
  }
 ]
};
if(typeof window!=='undefined'){window.MOCK=MOCK;}
